# WARNING!!!!!
#
# This is the development version of the compose file and should not
# be used in production as it does not have a secure SECRET_KEY or
# secure database passwords. In addition, it is missing an nginx frontend
# to server up the static content when the gunicorn command is run instead
# of the development server.

version: '3'

services:
  pegboard:
    build: .
    image: pegboard:latest

    ports:
      - '8000:8000'
    restart: unless-stopped
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-development-key-not-production
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - SQL_ENGINE=django.db.backends.mysql
      - SQL_DATABASE=pegboard
      - SQL_USER=pegboard
      - SQL_PASSWORD=pegboard
      - SQL_HOST=pegdb
      - SQL_PORT=3306
    volumes:
        - ./app:/code
    depends_on:
      - pegdb
    command: python manage.py runserver 0.0.0.0:8000
    # command: gunicorn pegboard.wsgi:application --bind 0.0.0.0:8000
 
    # uncomment the following, then start up the containers, create a
    # login with docker exec in order to use import ipdb statements in
    # the server code.
    # command: /bin/bash -c /bin/bash
    # stdin_open: true
    # tty: true

  pegdb:
    image: mysql:8.0.28
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pegboard
      - MYSQL_DATABASE=pegboard
      - MYSQL_USER=pegboard
      - MYSQL_PASSWORD=pegboard
